version: '3'
services:
  cli:
    image: ruby:2-stretch
    volumes:
      - .:/app
      - cache:/bundles
    environment:
      - BUNDLE_PATH=/bundles
      - GITLAB_API_URL=${GITLAB_API_URL}
      - GITLAB_API_KEY=${GITLAB_API_KEY}
    working_dir: /app
volumes:
  cache:
